server:
  port: 8080

spring:
  application:
    name: zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8000/eureka/
    register-with-eureka: false

zuul:
  routes:
    inventory:
      path: /inventory/**
      serviceId: inventory-system
      url: http://localhost:8081/inventory
