server:
  port: 8000
spring:
  application:
    name: Eureka Server
eureka:
  server:
    eviction-interval-timer-in-ms: 1000
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: eureka-server
